import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { initializeWikiCabinet } from "./config";
import { SourceStore } from "./source-store";
import { encodeSourceManifest } from "./manifest";
import { RawPublicationStore } from "./raw-publication";
import { SourceNormalizationService } from "./normalizers";
import { textHash } from "./wiki-publication";
import { migrateRawLayout } from "./raw-layout";
import { readRawSource } from "./raw-reader";

test("legacy Raw migration preserves identities, evidence, citations and future updates", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "raw-layout-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.writeFile(path.join(root, ".cabinet"), "kind: root\nname: Layout\n");
  const cabinet = await initializeWikiCabinet(root, { enabled: true });
  const original = "Notes/Apple Notes/Programming/Study.md";
  await fs.mkdir(path.dirname(path.join(root, original)), { recursive: true });
  await fs.writeFile(path.join(root, original), "# Original\nKeep me.");
  const store = new SourceStore(root);
  const entry = await store.register({ mode: "managed", managedLocation: { kind: "cabinet", path: original }, title: "Study", classification: "notes", roomPath: null });
  assert.equal(entry.source.rawPath, "raw/Notes/Apple Notes/Programming/Study");
  const destination = entry.source.rawPath;
  const legacy = `raw/legacy/study-${entry.source.id}`;
  await fs.mkdir(path.join(root, "raw/legacy"), { recursive: true });
  await fs.rename(path.join(root, destination), path.join(root, legacy));
  entry.source.rawPath = legacy; delete entry.source.mirroredFrom;
  await fs.writeFile(path.join(root, legacy, "manifest.yaml"), encodeSourceManifest(entry, cabinet));
  const normalize = async (value: string) => new SourceNormalizationService().normalize({ path: original, bytes: Buffer.from(value), contentHash: textHash(value) });
  const publisher = new RawPublicationStore(root);
  const first = await publisher.publishInitial(entry.source.id, await normalize("# Original\nKeep me."));
  // Recreate the legacy redundant original and its matching receipt.
  const capture = `${legacy}/v1/capture/${original}`;
  await fs.mkdir(path.dirname(path.join(root, capture)), { recursive: true });
  await fs.writeFile(path.join(root, capture), "# Original\nKeep me.");
  const metadata = JSON.stringify({ schemaVersion: 1, original: `capture/${original}` }) + "\n";
  await fs.writeFile(path.join(root, legacy, "v1/capture.json"), metadata);
  const receiptPath = path.join(root, `.cabinet-state/llm-wiki/publications/${entry.source.id}/v1/receipt.json`);
  const receipt = JSON.parse(await fs.readFile(receiptPath, "utf8"));
  receipt.files.push({ path: `capture/${original}`, sha256: textHash("# Original\nKeep me."), size: Buffer.byteLength("# Original\nKeep me.") });
  Object.assign(receipt.files.find((file: { path: string }) => file.path === "capture.json"), { sha256: textHash(metadata), size: Buffer.byteLength(metadata) });
  await fs.writeFile(receiptPath, JSON.stringify(receipt));
  assert.equal((await migrateRawLayout(root)).migrated, 1);
  const migrated = (await store.get(entry.source.id))!;
  assert.equal(migrated.source.rawPath, destination);
  assert.equal(migrated.versions[0].id, first.versions[0].id);
  assert.equal((await readRawSource(root, `${legacy}/v1/source.md`)).kind, "source");
  await assert.rejects(fs.access(path.join(root, destination, "v1/capture")));
  assert.equal(await fs.readFile(path.join(root, original), "utf8"), "# Original\nKeep me.");
  const unchanged = await publisher.publishUpdate(entry.source.id, first.versions[0].id, await normalize("# Original\nKeep me."));
  assert.equal(unchanged.versions.length, 1);
  const second = await publisher.publishUpdate(entry.source.id, first.versions[0].id, await normalize("# Updated\nNew evidence."));
  assert.equal(second.versions.length, 2);
  assert.equal((await readRawSource(root, `${legacy}/v1/source.md`)).kind, "source");
  assert.equal((await migrateRawLayout(root)).migrated, 0);
});
