/** Cabinet-authored Wiki operating documents, adapted from the Karpathy
 * llm-wiki-bootstrap skill. SCHEMA.md is written once and then user-editable;
 * the concept-table and overview templates seed agent-maintained pages. */

export function wikiSchemaTemplate(cabinetName: string): string {
  return `# ${cabinetName} Wiki

> Auto-generated by Cabinet. This file instructs the LLM agent how to operate on this wiki. It is safe to edit.

## Identity

You are the maintainer of the **${cabinetName} Wiki**, the knowledge base of this Cabinet.

You own the \`wiki/\` directory entirely. Create, update, and delete pages as needed, except \`wiki/index.md\` and \`wiki/log.md\`, which Cabinet maintains. Never modify files in \`raw/\`; those are immutable source documents.

## Directory Layout

\`\`\`text
raw/            # Source documents (read-only), mirroring the notes hierarchy
raw/<note path>/v<n>/source.md  # Captured markdown for one source version
wiki/           # Your pages (read-write)
wiki/index.md   # Content catalog. Cabinet regenerates it after every change
wiki/concept-table.md # Maintained concept map. Update on every concept change
wiki/log.md     # Append-only operation log. Cabinet appends entries
wiki/overview.md # High-level synthesis. Revise as understanding deepens
\`\`\`

## Page Types

| Type | Filename pattern | Purpose |
| --- | --- | --- |
| Source summary | \`wiki/sources/{slug}.md\` | One per ingested source. Key claims, data, quotes. Generated by Cabinet from checked quotes; you may enrich the body (wikilinks, Limitations) but must not edit its frontmatter, \`## Evidence\`, or \`## Source provenance\`. |
| Entity | \`wiki/entities/{name}.md\` | Person, org, place, product: anything with identity. |
| Concept | \`wiki/concepts/{name}.md\` | Idea, theory, framework, method. |
| Concept table | \`wiki/concept-table.md\` | Maintained matrix of concepts, definitions, relationships, sources, confidence, and maintenance notes. |
| Comparison | \`wiki/comparisons/{a}-vs-{b}.md\` | Side-by-side analysis of two+ entities or concepts. |
| Synthesis | \`wiki/synthesis/{topic}.md\` | Cross-source analysis on a theme. |
| Overview | \`wiki/overview.md\` | Top-level narrative of the entire knowledge base. |

## Page Format

Every wiki page MUST have YAML frontmatter:

\`\`\`yaml
---
title: Page Title
type: source-summary | entity | concept | concept-table | comparison | synthesis | overview
created: YYYY-MM-DD
updated: YYYY-MM-DD
sources: [source-slug-1, source-slug-2]
tags: [tag1, tag2]
---
\`\`\`

Entity pages also carry \`subtype: person | organization | place | product | event | software | other\`.

In \`sources:\` list source-summary slugs (e.g. \`[anthropic-calls-for-global-freeze-in-ai-development]\`), not raw paths.

Body conventions:

- Use \`[[wikilink]]\` syntax for internal cross-references
- Cite sources inline: \`[Source Title](../sources/{slug}.md)\`
- Flag contradictions explicitly: \`> ⚠️ CONTRADICTION: Source A claims X, Source B claims Y.\`
- Mark confidence levels where relevant: \`(high confidence)\`, \`(tentative)\`, \`(single-source)\`

## Operations

Runs are unattended: never pause to ask the user questions; decide, act, and report.

### Ingest

Trigger: Cabinet tells you a source summary page exists at \`wiki/sources/{slug}.md\`.

Protocol:

1. Read the source summary completely; read the raw evidence file only if needed (it is read-only)
2. Read \`wiki/index.md\` and \`wiki/concept-table.md\` for the current map
3. Update existing entity and concept pages that the source touches
4. Create new entity/concept pages if the source introduces them
5. Check for contradictions with existing wiki content, flag in both pages
6. Turn the summary's Entities/Concepts candidate lists into \`[[wikilinks]]\` and cite the new or existing pages
7. Update \`wiki/concept-table.md\` for every concept created, renamed, merged, split, deleted, or materially revised (skipped during batch ingests; Cabinet runs a consolidate pass afterwards)
8. Review \`wiki/overview.md\`: if the new source changes the big picture, revise it
9. Never edit \`wiki/index.md\` or \`wiki/log.md\`; Cabinet maintains them

### Consolidate

Trigger: Cabinet asks for a consolidation after a batch of ingests.

Protocol:

1. Re-read all \`wiki/sources\`, \`entities\`, \`concepts\`, \`comparisons\`, and \`synthesis\` pages
2. Rebuild \`wiki/concept-table.md\` so it has one row per concept page, plus the Concept Clusters section
3. Revise \`wiki/overview.md\` as the executive synthesis (Scope, Current State, Key Themes, Open Questions)
4. Create synthesis or comparison pages where cross-source themes justify them

### Lint

Trigger: Cabinet asks for a health check.

Protocol:

1. Read \`wiki/index.md\`, \`wiki/concept-table.md\`, and all listed pages
2. Check for contradictions, stale claims, orphan pages, missing pages, concept-table drift, weak areas, missing cross-references, missing frontmatter, tag inconsistency
3. Fix automatically what is safe: broken wikilinks, orphan cross-links, concept-table drift, missing frontmatter, missing backlinks, tag consistency
4. Do NOT resolve content contradictions or delete pages; list them as deferred
5. Report a numbered list: issues found, fixed, deferred

## Index Protocol

\`wiki/index.md\` is maintained by Cabinet. It lists Core Maps, Sources, Entities, Concepts, Comparisons, and Synthesis tables sorted alphabetically. Do not edit it; keep frontmatter accurate so the index stays correct.

## Concept Table Protocol

\`wiki/concept-table.md\` is the compressed map of durable concepts. Maintain this structure:

\`\`\`markdown
## Maintenance Rules

## Concept Clusters
| Cluster | Concepts | Current interpretation |
| --- | --- | --- |

## Concepts
| Concept | Working definition | Role in this wiki | Sources | Related pages | Status | Maintenance note |
| --- | --- | --- | --- | --- | --- | --- |
\`\`\`

Rules:

- Keep one row for every durable concept page under \`wiki/concepts/\`.
- Update the row whenever a concept page is created, renamed, deleted, merged, split, or materially revised.
- Keep rows sorted alphabetically by concept name.
- Keep definitions concise and evidence-aware; link to the full concept page for detail.
- Use \`Status\` values such as \`high confidence\`, \`single-source\`, \`tentative\`, \`needs sources\`, or \`contradicted\`.
- Column headers stay English as protocol identifiers; row content follows the language of the relevant concept page.

## Log Protocol

\`wiki/log.md\` is append-only and maintained by Cabinet. Every operation adds an entry in the form:

\`\`\`text
## [YYYY-MM-DD] {operation} | {subject}
- {details as bullet points}
\`\`\`

## Conventions

- Filenames: lowercase, hyphens, no spaces. e.g. \`attention-is-all-you-need.md\`
- One concept per page. Split if a page grows beyond two distinct ideas.
- Prefer tables for structured comparisons.
- When uncertain, note uncertainty explicitly rather than omitting.
- Always preserve the source's original claims: summarize faithfully, critique separately.
- In \`sources\` frontmatter, use source-summary slugs only.

## Language

All wiki content MUST match the language of the source being ingested:

1. Detect the source's primary language on each ingest.
2. Source summaries, entity pages, concept pages, and derived content use the source's language.
3. Structural elements stay English: frontmatter keys, \`type\` values, filename slugs, and table column headers.
4. Cross-source pages (comparisons, synthesis, overview) use the language of the majority of sources.
`;
}

export function conceptTableTemplate(date: string): string {
  return `---
title: Concept Table
type: concept-table
created: ${date}
updated: ${date}
sources: []
tags: [concept-map, navigation, maintenance]
---

> This table is the wiki's compressed concept map. It complements \`wiki/index.md\`: the index catalogs pages; this table explains what the durable concepts mean, how they relate, and what needs maintenance.

## Maintenance Rules

- Keep one row for every durable concept page under \`wiki/concepts/\`.
- Update this table whenever a concept page is created, renamed, deleted, merged, split, or materially revised.
- Keep rows sorted alphabetically by concept name.
- Keep definitions concise and evidence-aware; link to the full concept page for detail.
- Use \`Status\` values such as \`high confidence\`, \`single-source\`, \`tentative\`, \`needs sources\`, or \`contradicted\`.
- Column headers stay English as protocol identifiers; row content follows the language of the relevant concept page.

## Concept Clusters

| Cluster | Concepts | Current interpretation |
| --- | --- | --- |

## Concepts

| Concept | Working definition | Role in this wiki | Sources | Related pages | Status | Maintenance note |
| --- | --- | --- | --- | --- | --- | --- |
<!-- New concept rows go here -->
`;
}

export function overviewTemplate(cabinetName: string, date: string): string {
  return `---
title: Overview
type: overview
created: ${date}
updated: ${date}
sources: []
tags: []
---

# ${cabinetName} Wiki: Overview

> This page is the top-level synthesis of the entire knowledge base.
> It is revised as sources are ingested and understanding deepens.

## Scope

Knowledge captured in the ${cabinetName} Cabinet.

## Current State

No sources ingested yet. The first ingest will seed this page.

## Key Themes

<!-- Themes will emerge as sources accumulate -->

## Open Questions

<!-- Questions worth investigating will be noted here -->
`;
}

export function logTemplate(date: string): string {
  return `# Log

> Append-only chronological record of all wiki operations.
> Each entry: \`## [YYYY-MM-DD] operation | subject\`
> Parse with: \`grep "^## \\[" wiki/log.md | tail -10\`

## [${date}] init | Wiki created
- Scaffolded by Cabinet
- Schema: SCHEMA.md (single source of truth)
`;
}
